touray/urls.py
from django.urls import path
from . import views

app_name = 'touray'

urlpatterns = [
    path('', views.home, name='home'),
    path('resources/', views.resources, name='resources'),
    path('post/', views.newsFeed, name='post'),
    path('donation/', views.donation, name='donation'),
    path('mosque/', views.mosque, name='mosque'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

touray_site/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('touray.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

touray/models.py
from django.db import models


class Posts(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    author = models.CharField(max_length=100)
    rank = models.CharField(max_length=100)


class Audio(models.Model):
    title = models.CharField(max_length=100)
    audio_src = models.FileField(upload_to='jassong/Audios/')


# class Videos(models.Model):
#     title = models.CharField(max_length=255)
#     video_src = models.FileField(upload_to='jassong/Videos/')
#
#
# class Images(models.Model):
#     title = models.CharField(max_length=255)
#     upload = models.FileField(upload_to='jassong/Images/')
#

touray/views.py
from django.shortcuts import render
from .models import Posts, Audio


def home(request):
    return render(request, 'touray/home.html')


def resources(request):
    audious = Audio.objects.all()
    context = {"audious": audious}
    return render(request, 'touray/resources.html', context)


def newsFeed(request):
    posts = Posts.objects.all()
    context = {'posts': posts}
    return render(request, 'touray/post.html', context)


def donation(request):
    return render(request, 'touray/donation.html')


def mosque(request):
    return render(request, 'touray/mosque.html')


def about(request):
    return render(request, 'touray/about.html')


def contact(request):
    return render(request, 'touray/contact.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css"
          referrerpolicy="no-referrer"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/alpinejs/3.10.4/cdn.js"
            integrity="sha512-Wdmlp5V7fHwqpofZO7pNl3za/3XN1nojhfo2q212hO+5A5H3fMj/zI++8xQVQBVwkMDqN8vska0T8LvCWwn48w=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/alpinejs/3.10.4/cdn.min.js"
            integrity="sha512-Zq7JviKo/hIy704ZFZo18ULX3LjAcbM2Qft92HrEyNCXcEtt2+0On8DaEb7Dce+AbdS+jBpBgKSD2P/0WfKhIQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://unpkg.com/flowbite@1.5.3/dist/flowbite.js"></script>
</head>
<body>
<!--    navbar-->
<nav class="bg-gray-600 border-gray-200 px-2 sm:px-4 py-2.5 dark:bg-gray-900">
    <div class="container flex flex-wrap justify-between items-center mx-auto">
        <a class="flex items-center" href="/">
            <img alt="touray logo" class="mr-3 h-6 sm:h-9" src="{% static 'images/sj-1.png' %}">
            <span class="self-center text-2xl text-white font-semibold whitespace-nowrap ">JassongTouray Foundation</span>
        </a>
        <button aria-controls="navbar-default" aria-expanded="false"
                class="visible inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                data-collapse-toggle="navbar-default" type="button">
            <span class="sr-only">Open main menu</span>
            <svg aria-hidden="true" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20"
                 xmlns="http://www.w3.org/2000/svg">
                <path clip-rule="evenodd"
                      d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                      fill-rule="evenodd"></path>
            </svg>
        </button>
        <div class="hidden w-full md:block md:w-auto" id="navbar-default">
            <ul class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                <li>
                    <a aria-current="page"
                       class="block py-2 pr-4 pl-3 text-white bg-gray-400 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white"
                       href="/">Home</a>
                </li>
                <li>
                    <a class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
                       href="{% url 'touray:about'%}">About</a>
                </li>
                <li>
                    <a class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
                       href="{% url 'touray:donation' %}">Donation</a>
                </li>
                <li>
                    <a class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
                       href="{% url 'touray:post' %}">Posts</a>
                </li>
                <li>
                    <a class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
                       href="{% url 'touray:resources' %}">Media</a>
                </li>
                <li>
                    <a class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
                       href="{% url 'touray:contact' %}">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="mb-12  bg-opacity-80">
    {% block content %}{% endblock %}
</div>
<!--footer-->

<footer class="p-4 bg-gray-600 text-white sm:p-6 dark:bg-gray-800">
    <div class="md:flex md:justify-between">
        <div class="mb-6 md:mb-0">
            <a class="flex items-center" href="https://flowbite.com/">
                <!--                <img alt="FlowBite Logo" class="mr-3 h-8" src="/docs/images/logo.svg">-->
                <span class="self-center text-2xl font-semibold font-mono whitespace-nowrap dark:text-white">Sheikh Jassong Touray Foundation</span>
            </a>
        </div>
        <div class="grid grid-cols-2 gap-8 sm:gap-6 sm:grid-cols-3">
            <div>
                <h2 class="mb-6 text-sm font-semibold text-white uppercase dark:text-white">Follow us</h2>
                <ul class="text-gray-600 dark:text-gray-100">
                    <li class="mb-4 text-gray-300">
                        <a class="hover:underline "
                           href="/">twitter</a>
                    </li>
                    <li class="text-gray-300">
                        <a class="hover:underline" href="https://web.facebook.com/profile.php?id=100071171781750">Facebook</a>
                    </li>
                </ul>
            </div>
            <div>
                <h2 class="mb-6 text-sm font-semibold text-white uppercase dark:text-white">Legal</h2>
                <ul class="text-gray-600 dark:text-gray-400">
                    <li class="mb-4 text-gray-300">
                        <a class="hover:underline" href="#">Privacy Policy</a>
                    </li>
                    <li class="text-gray-300">
                        <a class="hover:underline" href="#">Terms &amp; Conditions</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8">
    <div class="sm:flex sm:items-center sm:justify-between">
        <span class="text-sm text-gray-300 sm:text-center dark:text-gray-400">© 2022 <a class="hover:underline"
                                                                                        href="/">Sheikh Jassong Touray Foundation.™</a> All Rights Reserved.
        </span>
        <div class="flex mt-4 space-x-6 sm:justify-center sm:mt-0">
            <a class="text-gray-300 hover:text-gray-900 dark:hover:text-white"
               href="pjtfoundation2019@gmail.com">
                <svg clip-rule="evenodd" fill-rule="evenodd" height="24" width="24" xmlns="http://www.w3.org/2000/svg">
                    <path d="M22.288 21h-20.576c-.945 0-1.712-.767-1.712-1.712v-13.576c0-.945.767-1.712 1.712-1.712h20.576c.945 0 1.712.767 1.712 1.712v13.576c0 .945-.767 1.712-1.712 1.712zm-10.288-6.086l-9.342-6.483-.02 11.569h18.684v-11.569l-9.322 6.483zm8.869-9.914h-17.789l8.92 6.229s6.252-4.406 8.869-6.229z"/>
                </svg>
            </a>

            <a class="text-gray-300 hover:text-gray-900 dark:hover:text-white"
               href="https://web.facebook.com/Sheikh-Jasong-Touray-Foundation-105919497417878">
                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                    <path clip-rule="evenodd"
                          d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z"
                          fill-rule="evenodd"></path>
                </svg>
            </a>
            <a class="text-gray-300 hover:text-gray-900 dark:hover:text-white"
               href="">
                <svg height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
                    <path d="M4.652 0h1.44l.988 3.702.916-3.702h1.454l-1.665 5.505v3.757h-1.431v-3.757l-1.702-5.505zm6.594 2.373c-1.119 0-1.861.74-1.861 1.835v3.349c0 1.204.629 1.831 1.861 1.831 1.022 0 1.826-.683 1.826-1.831v-3.349c0-1.069-.797-1.835-1.826-1.835zm.531 5.127c0 .372-.19.646-.532.646-.351 0-.554-.287-.554-.646v-3.179c0-.374.172-.651.529-.651.39 0 .557.269.557.651v3.179zm4.729-5.07v5.186c-.155.194-.5.512-.747.512-.271 0-.338-.186-.338-.46v-5.238h-1.27v5.71c0 .675.206 1.22.887 1.22.384 0 .918-.2 1.468-.853v.754h1.27v-6.831h-1.27zm2.203 13.858c-.448 0-.541.315-.541.763v.659h1.069v-.66c.001-.44-.092-.762-.528-.762zm-4.703.04c-.084.043-.167.109-.25.198v4.055c.099.106.194.182.287.229.197.1.485.107.619-.067.07-.092.105-.241.105-.449v-3.359c0-.22-.043-.386-.129-.5-.147-.193-.42-.214-.632-.107zm4.827-5.195c-2.604-.177-11.066-.177-13.666 0-2.814.192-3.146 1.892-3.167 6.367.021 4.467.35 6.175 3.167 6.367 2.6.177 11.062.177 13.666 0 2.814-.192 3.146-1.893 3.167-6.367-.021-4.467-.35-6.175-3.167-6.367zm-12.324 10.686h-1.363v-7.54h-1.41v-1.28h4.182v1.28h-1.41v7.54zm4.846 0h-1.21v-.718c-.223.265-.455.467-.696.605-.652.374-1.547.365-1.547-.955v-5.438h1.209v4.988c0 .262.063.438.322.438.236 0 .564-.303.711-.487v-4.939h1.21v6.506zm4.657-1.348c0 .805-.301 1.431-1.106 1.431-.443 0-.812-.162-1.149-.583v.5h-1.221v-8.82h1.221v2.84c.273-.333.644-.608 1.076-.608.886 0 1.18.749 1.18 1.631v3.609zm4.471-1.752h-2.314v1.228c0 .488.042.91.528.91.511 0 .541-.344.541-.91v-.452h1.245v.489c0 1.253-.538 2.013-1.813 2.013-1.155 0-1.746-.842-1.746-2.013v-2.921c0-1.129.746-1.914 1.837-1.914 1.161 0 1.721.738 1.721 1.914v1.656z"/>
                </svg>
            </a>
            <!--            <a class="text-gray-300 hover:text-gray-900 dark:hover:text-white" href="">-->
            <!--                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">-->
            <!--                    <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84"></path>-->
            <!--                </svg>-->
            <!--            </a>-->

        </div>
    </div>
</footer>

</body>
</html>

touray/templates/touray/about.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style>
    .custom-img {
        background-image: url('{% static 'images/backgroud.jpg' %}')
    }


</style>

<header class="flex items-center justify-center h-screen mb-12 bg-fixed bg-center bg-cover custom-img">
    <div class="p-5 text-2xl text-white bg-purple-300 bg-opacity-50 rounded-xl font-mono">
        Sheikh Jassong Touray Foundation
    </div>
</header>

<div class="max-auto p-4">
    <div class="bg-gray-200 mx-auto w-ful md:w-1/2 rounded-xl shadow-xl">
        <h1 class="uppercase text-center text-gray-900 pt-6 text-3xl font-bold font-mono">about-us</h1>
        <div class="px-12 py-6">
            <p class="leading-loose text-center font-mono text-lg">
                The Sheikh Jassong Touray Foundation was based on the maining and promooting the
                legacy of late Sheikh Pa Jassong Touray. In our efforts to promote and maintain the legacy of our Grand
                Scholar and marabou the late Sheikh Pa Jassong Touray, We are embarking on a fund raising request from
                Donor Agencies, International Partners, NGO's and Charitable Organisations, to maintain his work.
                He led a Humble and Noble life. Most of His work was concentrated in the areas of Education, Health,
                Religion, Infrastructural Development, and work for Humanity and Agriculture.
            </p>
        </div>
    </div>

</div>

{% endblock %}

touray/templates/touray/contact.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style>
    .custom-img {
        background-image: url('{% static 'images/backgroud.jpg' %}')
    }





</style>

<header class="flex items-center justify-center h-screen mb-12 bg-fixed bg-center bg-cover custom-img">
    <div class="p-5 text-2xl text-white bg-purple-300 bg-opacity-50 rounded-xl font-mono">
        Sheikh Jassong Touray Foundation
    </div>
</header>

<div class="">
    <div class="md:flex bg-gray-200 w-3/4 mx-auto p-6 rounded-xl">
        <div class="w-full md:flex-col md:w-1/2">
            <h1 class="text-center pt-12 text-gray-900 text-3xl uppercase font-mono">contact-us</h1>
            <div class="my-12 ">
                <p class="text-gray-900 pb-2">Address: <span class="font-mono">No.8 Kairaba Avenue, Serrekunda,The Gambia</span>
                </p>
                <p class="text-gray-900 pb-2">Phone: <span class="px-4 font-mono">+9173332, 7593739, 7471086</span></p>
                <p class="text-gray-900 pb-2">Gmail Address: <span
                        class="px-4 font-mono">pjtfoundation2019@gmail.com</span></p>
                <a href="https://web.facebook.com/profile.php?id=100071171781750"><p class="text-gray-900 pt-6">
                    Facebook: <span
                        class="px-4 font-mono">https://web.facebook.com/profile.php?id=100071171781750</span>
                </p></a>
            </div>

        </div>
        <div class="w-full md:flex-col md:w-1/2">
            <img alt="jasson" src="{% static 'images/jasson.jpg'%}">
        </div>
    </div>
</div>


{% endblock %}

touray/templates/touray/home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style>
    .custom-img {
        background-image: url('{% static 'images/backgroud.jpg' %}')
    }

    .jasson-img {
     background-image: url("{% static 'images/jasson.jpg' %}");
    }

</style>

<header class="flex items-center justify-center h-screen mb-12 bg-fixed bg-center bg-cover custom-img">
<div class="p-5 text-2xl text-white bg-purple-300 bg-opacity-50 rounded-xl font-mono">
    Sheikh Jassong Touray Foundation
</div>
</header>
<div class="md:flex bg-gray-200 p-10 bg-opacity-80">
    <section class="md:flex-col mx-auto max-w-xl px-4 py-2">
        <h2 class="pb-6 text-md text-green-600">IN THE NAME OF ALLAH, THE MOST GRACIOUS, THE MOST MERCIFUL</h2>
        <p class="text-justify leading-loose pb-6">In our efforts to promote and maintain the legacy of our Grand
            Scholar
            and marabou the late Sheikh Pa Jassong
            Touray. We are embarking on a fund raising request from Donor Agencies,
            International Partners, NGO's and
            Charitable Organisations, to maintain his work.
        </p>
        <p class="text-justify leading-loose">
            He spent 40 years searching for knowledge and spent His entire life Teaching
            and treating people from all over the world.
            He led a Humble and Noble life. Most of His work was concentrated in the areas of Education,
            Health, Religion, Infrastructural Development, and work for Humanity and Agriculture.
        </p>

        <button class="bg-blue-500 px-6 py-2 rounded-full text-white mt-6">Donate Now</button>
    </section>

    <section class="invisible md:visible md:flex-col mx-auto max-w-xl h-auto">
        <img alt="jassong" class="h-52" src="{% static 'images/jasson.jpg'%}">
    </section>
</div>

<section
        class="container flex items-center justify-center h-screen m-auto mb-12 bg-fixed bg-center bg-cover jasson-img"
>
    <div class="p-5 text-2xl text-white bg-purple-300 bg-opacity-50 rounded-xl">
        Buiba Dallo Projects
    </div>
</section>

<h3 class="uppercase text-center text-3xl font-bold font-mono">Founders</h3>
<div class="md:flex px-6">
    <div class="md:flex-col mx-auto w-full md:max-w-sm bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
        <a href="#">
            <img alt="" class="rounded-t-lg" src="{% static 'images/sheikh-jassong-touray.jpg'%}">
        </a>
        <div class="p-5">
            <a href="#">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Sheikh Jassong Touray</h5>
            </a>
            <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">CALIPH GENERAL OF JASSONG AND BUIBA (1911-1991).</p>
        </div>
    </div>


    <div class="md:flex-col mx-auto my-4 md:my-0 w-ful md:max-w-sm bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
        <a href="#">
            <img alt="" class="rounded-t-lg" src="{% static 'images/khalifa.jpg'%}">
        </a>
        <div class="p-5">
            <a href="#">
                <h5 class="mb-2 text-center uppercase text-xl text-green-600 font-bold tracking-tight text-gray-900 dark:text-white">The Current Calipha</h5>
            </a>
            <p class="mb-3 font-normal text-center text-gray-700 dark:text-gray-400">Sheikh Jassong Touray Foundation.</p>
            <a class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
               href="#">
                Donate
                <svg aria-hidden="true" class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20"
                     xmlns="http://www.w3.org/2000/svg">
                    <path clip-rule="evenodd"
                          d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                          fill-rule="evenodd"></path>
                </svg>
            </a>
        </div>
    </div>


    <div class="md:flex-col mx-auto w-full md:max-w-sm bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
        <a href="#">
            <img alt="" class="rounded-t-lg" src="{% static 'images/jasson.jpg'%}">
        </a>
        <div class="p-5">
            <a href="#">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white text-center">Buiba Dallo Projects</h5>
            </a>
            <p class="mb-3 font-normal text-gray-700 dark:text-gray-400 text-center">Sheikh Jassong Foundation. click button below to donate 👇</p>
            <a class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
               href="#">
                Read more
                <svg aria-hidden="true" class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20"
                     xmlns="http://www.w3.org/2000/svg">
                    <path clip-rule="evenodd"
                          d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                          fill-rule="evenodd"></path>
                </svg>
            </a>
        </div>
    </div>
</div>


{% endblock %}

touray/templates/touray/post.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container bg-gray-300 max-w-full md:flex md:flex-wrap p-4">
    <h1 class="capitalize text-3xl font-bold font-mono mx-4 text-blue-700">news feed</h1>
    {% for post in posts %}
        <div class="mx-auto shadow-lg max-w-lg mb-2 p-6 bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
            <a href="#">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ post.title }}</h5>
            </a>
            <p class="mb-3 text-center justify-text font-normal text-gray-700 dark:text-gray-400">{{ post.body }}</p>
            <figcaption class="flex justify-center items-center space-x-3">
                <img alt="profile picture"
                     class="w-9 h-9 rounded-full"
                     src="{% static 'images/jasson.jpg' %}">
                <div class="space-y-0.5 font-medium dark:text-white text-left">
                    <div>{{ post.author }}</div>
                    <div class="text-sm font-light text-gray-500 dark:text-gray-400">{{ post.rank }}</div>
                </div>
            </figcaption>
        </div>
    {% endfor %}
</div>

{% endblock %}